const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  kaa: "kaa",
  action: "amallar",
  create: "jaratıw",
  delete: "öshiriw",
  close: "jabıw",
  update: "jañalaw",
  basket: "Sebet",
  transfer: "Ötkiziw",
  continue: "rastlaw",
  login: {
    welcome: "TMAǵa xosh kelipsiz",
    title: "Kiriw",
    password: "Parol",
    enter: "kiriw",
    wrongpasswor: "Dúres emes paydalanıwshı atı yaki parol! Qaıtadan áwlep kóriń",
  },

  alerts: {
    password_incorreect:
      "dúres emes parol: parol kemende bir bas harip, belgisi hám san bolıwi, hám 6 dan 30 belgige shekem bolıwi kerek",
    confirmdelete: "Haqiqattan óshirgenińizge isenimli ma?",
    ok: "ok",
    no: "bekar qılıw",
    inputError: "Bos maǵlıwmat engizbeniń",
    nodelete: "ruqsat joq",
    deleted: "Óshirildi",
    added: "Jaratıldı",
    edited: "Jañalandı",
    slownetwork: "Internet jay yaki bar emes",
    warning: "námadir dúres emes, qaytadan áwlep kóriń",
  },

  sidebar: {
    news_category: "Jańalıqlar kategoriyası",
    library_category: "Kitapxana kategoriyası",
    library: "Kitapxana",
    faq_category: "FAQ kategoriyası",
    faq: "FAQ",
    advertisement: "Reklama",
    advertisement_category: "Reklama kategoriyası",
    anouncement: "Jarıyalaw",
    anouncement_category: "Jarıyalaw kategoriyası",
    anons_network_category: "Jarıyalaw torı kategoriyası",
    anons_network_link: "Jarıyalaw torı siltemesi",
    anons_faq: "Jarıyalaw FAQ",
    story: "Hikaye",
    videos: "Videolar",
    category: "Kategoriya",
    reviews: "Gimarətlər",
    admins: "Administratorlar",
    news: "Jańalıqlar",
    type: "Túr",
    exit: "Shığıw",
    role: "Role",
    top_news: "Eng jańa jańalıqlar",
  },

  home: {
    start_time: "baslaw waqıtı",
    end_time: "ayaqlaw waqıtı",
    budget: "byudjet",
    clients: "klientler",
    total_profit: "jalpı payda",
    expenses: "shǵınlar",
  },

  table: {
    link: "Silteme",
    construction_date: "qurılıw waqıtı",
    zip_code: "poçta kodi",
    floors: "qabatlar",
    video: "video",
    state: "oblıs",
    city: "qala",
    search_by: (e) => `${e} boyınsha izlew`,
    loading: "Júklenıwde...",
    not_found: "Maǵlıwmat tabılmadı",
    isTop: "Eng jańa jańalıqlar",
    isFree: "Teńge emes",
    main_image: "Muqaba sureti",
    images: "Suretler",
    file: "Fayl",
    grafik: "grafik",
    open_hour: "ashılıw waqıtı",
    close_hour: "jabılıw waqıtı",
    address: "Manzil",
    datefrom: (s, e) => `${s} den ${e} shekem`,
    fuel_type: "janǵarmay túri",
    max_speed: "máksimal tezlik",
    place: "jay",
    tinting: "tonirovka",
    baggage: "jükkana",
    conditioner: "konditsioner",
    false: "bar emes",
    true: "bar",
    view_count: "kóriwler sanı",
    lang: "til",
    star: "júldız",
    from: "dan",
    ordered: "buyırtma etildi",
    moving_from_country: "memlekettan shıǵıw",
    entered_to_country: "memleketke kiriw",
    delivered: "jetkizildi",
    creator: "jaratıwshı",
    types: "kóriw filtri",
    all: "barshası",
    by_category: "kategoriya boyınsha",
    by_client: "klient boyınsha",
    by_fesclient: "FES klient boyınsha",
    complated: "tamamlandı",
    active: "belgilengen",
    kurs: "kurs",
    card: "karta",
    cash: "naqt",
    delivery: "jetkiziw",
    pickup: "ólip ketiw",
    inactive: "belgilengen emes",
    payment_method: "tólew usılı",
    shipment_id: "jibermelik ID",
    custom_date: "árnaýlı waqıt",
    residual_amount: "qısqa maǵlıwmat",
    complated_amount: "to‘liq maǵlıwmat",
    image: "suret",
    exist: "bar",
    deliver_name: "jetkizgen adam",
    deliver_phone: "jetkizgen telefonı",
    truck_number: "asası",
    add_shipment: "Jibermelik qosıw",
    name: "Atı",
    sale: "jeńildik",
    title: "sarlawha",
    cost: "narx",
    author: "avtor",
    sale_amount: "jeńildik páyzı",
    subtitle: "qosımsha sarlawha",
    info: "maǵlıwmat",
    raiting: "reyting",
    like_count: "jaqısı körilgenler",
    download_count: "júklengenler",
    created_at: "jaratılǵan waqıt",
    amount: "mıqdar",
    overall_price: "Jalpı narx",
    payed_price: "tarkibi",
    status: "hálde",
    answer: "jawap",
    question: "suraq",
    country: "Kategoriya",
    country_number: "buyırtma nomeri",
    id: "ID",
    inn: "INN",
    total_amount: "jalpı mıqdar",
    type: "Avtomobil túri",
    car_name: "Avtomobil atı",
    method: "usıl",
    uses_date: "paydalanıw waqıtı",
    seria_id: "tomengí",
    sum: "Som",
    dollar: "valyutada",
    stock_id: "qor ID",
    price: "qosımsha sarlawha",
    client_id: "klient ID",
    new_price: "narx",
    direction: "baǵıt",
    product_name: "tovar atı",
    client_name: "klient atı",
    client_number: "klient nomeri",
    phone_number: "telefon nomeri",
    additional_info: "qosımsha maǵlıwmat",
    expenses_name: "shǵın atı",
    rows_per_page: "Bettegi qatarlar",
    date: "waqıt",
    rejected: "qabol etilmedi",
    accepted: "qabol etildi",
    reject: "qabol etbeý",
    accept: "qabol etiw",
    pending: "kútiliwde",
    warehouse: "Qor",
    employee: "qızmetker",
    location: "jaylasqan jeri",
  },
  modal: {
    add: "Qosıw",
    edit: "Ózgertiw",
    add_title: (title) => `${title} qosıw`,
    edit_title: (title) => `${title} ózgertiw`,
    addProduct: {
      addproduct: "Ónim qosıw",
      editproduct: "Ónimdi ózgertiw",
      count: "sanı",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "chegirma",
      addtocart: "Sebetke qosıw",
      sale_product: "Ónimdi satıw",
      total_price: "Jalpı baha",
    },
    addAdmins: {
      adddeliver: "Administrator qosıw",
      editdeliver: "Administratorni ózgertiw",
    },
    addNews: {
      addNews: "Jańalıq qosıw",
      editNews: "Jańalıqtı ózgertiw",
    },
    addBuilding: {
      addbuilding: "Gimarati qosıw",
      editbuilding: "Gimarattı ózgertiw",
    },
    addWarehouse: {
      title: "Brend qosıw",
      edit: "Brendi ózgertiw",
    },
  },
  
};

export default header;
