const header = {
  uz: "uzb",
  ru: "rus",
  en: "ing",
  kaa: "kaa",
  action: "ərekettar",
  create: "jasaw",
  delete: "öşiriw",
  close: "jabu",
  update: "jańalaw",
  basket: "Sebet",
  transfer: "Ötkiziw",
  continue: "rastlaw",
  login: {
    welcome: "TMA ǵa xosh kelipsiz",
    title: "Kiriw",
    password: "Parol",
    enter: "kiriw",
    wrongpasswor: "Login nemese parol nadurıs! Qayta urinip körıń",
  },

  alerts: {
    password_incorreect:
      "nadurıs parol: parolda keminde bir ulı hárip, belgisi hám san bolıwı kerek, uzınlıǵı 6 dan 30 ǵa shekem bolıwı kerek",
    confirmdelete: "Shaǵınan öşirmekshi boldıńız ba?",
    ok: "ok",
    no: "bekar qılıw",
    inputError: "Bos qiymet kiritbeń",
    nodelete: "ruqsat joq",
    deleted: "Sáwletli öşirildi",
    added: "Sáwletli jasaldi",
    edited: "Sáwletli jańalandı",
    slownetwork: "Internet asıl nemese joq",
    warning: "Bir nárse nadurıs boldı, qayta urinip körıń",
  },

  sidebar: {
    news_category: "Jańalıq kategoriyası",
    library_category: "Kitaphana kategoriyası",
    library: "Kitaphana",
    faq_category: "FAQ kategoriyası",
    faq: "FAQ",
    advertisement: "Reklama",
    advertisement_category: "Reklama kategoriyası",
    anouncement: "Xabarlama",
    anouncement_category: "Xabarlama kategoriyası",
    anons_network_category: "Anons tor kategoriyası",
    anons_network_link: "Anons tor siltemesi",
    anons_faq: "Anons FAQ",
    story: "Hikaye",
    videos: "Video",
    category: "Kategoriya",
    reviews: "Gımaratlar",
    admins: "Administratorlar",
    news: "Jańalıqlar",
    type: "tür",
    exit: "Shıǵıw",
    role: "rol",
    top_news: "Eng sońǵı jańalıqlar",
  },

  home: {
    start_time: "baslaw waqıtı",
    end_time: "ayaqlaw waqıtı",
    budget: "byudjet",
    clients: "múşteriler",
    total_profit: "jumlı payda",
    expenses: "shıǵım",
  },

  table: {
    link: "Silteme",
    construction_date: "qurılıs kúnı",
    zip_code: "poçta indeksi",
    floors: "qabatlar",
    video: "video",
    state: "shtat",
    city: "qala",
    search_by: (e) => `${e} boyınsha izlew`,
    loading: "Júklelewde...",
    not_found: "Maǵlıwmat tabılmadı",
    isTop: "Eng sońǵı jańalıq",
    isFree: "Teńsiz",
    main_image: "Muqaba sureti",
    images: "Suretler",
    file: "Fayl",
    grafik: "grafik",
    open_hour: "ashıw waqıtı",
    close_hour: "jabu waqıtı",
    address: "Mánzil",
    datefrom: (s, e) => `${s} den ${e} ǵa shekem`,
    fuel_type: "yanǵı mal türı",
    max_speed: "maksimal tezlik",
    place: "jay",
    tinting: "tinirow",
    baggage: "juq",
    conditioner: "konditsioner",
    false: "joq",
    true: "bar",
    view_count: "kóriw sanı",
    lang: "til",
    star: "juldız",
    from: "den",
    ordered: "buyırtılǵan",
    moving_from_country: "kelgen memleket",
    entered_to_country: "kirgen memleket",
    delivered: "jetkizildi",
    creator: "jasawshı",
    types: "kóriw filtri",
    all: "bárshesi",
    by_category: "kategoriya boyınsha",
    by_client: "múşteri boyınsha",
    by_fesclient: "FES múşteri boyınsha",
    complated: "tamamlanǵan",
    active: "belsendi",
    kurs: "kurs",
    card: "kart",
    cash: "qoldan",
    delivery: "jetkiziw",
    pickup: "alıw",
    inactive: "belsez",
    payment_method: "tólew úslini",
    shipment_id: "jetkiziw ID",
    custom_date: "arnawlı waqıt",
    residual_amount: "qısqa maǵlıwmat",
    complated_amount: "tolı maǵlıwmat",
    image: "sureti",
    exist: "bar",
    deliver_name: "jetkizgish atı",
    deliver_phone: "jetkizgish telefonı",
    truck_number: "nómir",
    add_shipment: "Jetkiziw qosıw",
    name: "Atı",
    sale: "chegirme",
    title: "taqırıw",
    cost: "báhasi",
    author: "avtor",
    sale_amount: "chegirme pıysı",
    subtitle: "qosımsha taqırıw",
    info: "maǵlıwmat",
    raiting: "reyting",
    like_count: "layklar",
    download_count: "júklewler",
    created_at: "jasalǵan waqıt",
    amount: "mıqdar",
    overall_price: "jumlı baha",
    payed_price: "tólew bólinbeleri",
    status: "xál",
    answer: "jawap",
    question: "sawáq",
    country: "Kategoriya",
    country_number: "buyırtpa nomeri",
    id: "ID",
    inn: "INN",
    total_amount: "jumlı somma",
    type: "avto türı",
    car_name: "avto atı",
    method: "usıl",
    uses_date: "qollanıw kúnı",
    seria_id: "tómengi",
    sum: "Somma",
    dollar: "valyutada",
    stock_id: "ombar ID",
    price: "qosımsha taqırıw",
    client_id: "múşteri ID",
    new_price: "báha",
    direction: "baǵıt",
    product_name: "óńim atı",
    client_name: "múşteri atı",
    client_number: "múşteri nomeri",
    phone_number: "telefon nomeri",
    additional_info: "qosımsha maǵlıwmat",
    expenses_name: "shıǵım atı",
    rows_per_page: "Bettegi qatarlaw",
    date: "waqıt",
    rejected: "qaýtarlanǵan",
    accepted: "qabul etilgen",
    reject: "qaýtarıw",
    accept: "qabul etiw",
    pending: "kútildi",
    warehouse: "Ombar",
    employee: "xızmetker",
    location: "ornı",
  },

  modal: {
    add: "Qosıw",
    edit: "Ózgertiw",
    add_title: (title) => `${title} qosıw`,
    edit_title: (title) => `${title} ózgertiw`,
    addProduct: {
      addproduct: "Ónim qosıw",
      editproduct: "Ónimdi ózgertiw",
      count: "mıqdar",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "chegirme",
      addtocart: "Sebetke qosıw",
      sale_product: "Ónimdi satıw",
      total_price: "Jumlı baha",
    },
    addAdmins: {
      adddeliver: "Admin qosıw",
      editdeliver: "Admindi ózgertiw",
    },
    addNews: {
      addnews: "Jańalıq qosıw",
      editnews: "Jańalıqtı ózgertiw",
      addNews: "Jańalıq qosıw",
      editNews: "Jańalıqtı ózgertiw",
    },
    addBuilding: {
      addbuilding: "Gımarat qosıw",
      editbuilding: "Gımarattı ózgertiw",
    },
    addWarehouse: {
      title: "Brend qosıw",
      edit: "Brendti ózgertiw",
      transfer_from_werhouse: "Bas ombardan ótkiziw",
      transfer_to_werhouse: "Ombar arqalı ótkiziw",
    },
    addExpenses: {
      title: "Shıǵım qosıw",
      edit: "Shıǵımdı ózgertiw",
    },
    addIncome: {
      title: "Kirime qosıw",
      edit: "Kirime ózgertiw",
    },
    addCategory: {
      title: "Kategoriya qosıw",
      edit: "Kategoriyanı ózgertiw",
      category: "Kategoriya",
      subcategory: "Tómengi kategoriya",
      subtitle: "Tómengi kategoriya qosıw",
      subedit: "Tómengi kategoriyanı ózgertiw",
    },
    addCompany: {
      title: "Kompaniya qosıw",
      edit: "Kompaniyanı ózgertiw",
      category: "Kompaniya",
      subcategory: "hisap esabı",
      subtitle: "Kompaniya hisap esabı qosıw",
      subedit: "Hisap esabın ózgertiw",
    },
  },
};

export default header;
