const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  action: "harakatlar",
  create: "yaratmoq",
  delete: "o'chirish",
  close:"yopish",
  update: "tahrirlash",
  basket: "Savatcha",
  transfer: "O'tkazish",
  continue:"tashdiqlash",
  login: {
    welcome: "TMA ga xush kelibsiz",
    title: "Kirish",
    password: "Parol",
    enter: "kirish",
    wrongpasswor: "Foydalanuvchi nomi yoki parol noto'g'ri! Qayta urinib ko'ring",
  },

  alerts: {
    password_incorreect:
      "parol noto'g'ri: parol kamida bitta katta harf, belgi va raqamdan iborat bo'lishi kerak, uzunligi 6 dan 30 gacha bo'lishi kerak",
    confirmdelete: "Haqiqatan ham o'chirmoqchimisiz?",
    ok: "ok",
    no: "bekor qilish",
    inputError: "Bo'sh ma'lumot kiritmang",
    nodelete: "ruxsat yo'q",
    deleted: "Muvaffaqiyatli o'chirildi",
    added: "Muvaffaqiyatli yaratildi",
    edited: "Muvaffaqiyatli o'zgartirildi",
    slownetwork: "Internet sekin yoki mavjud emas",
    warning: "biror narsa noto'g'ri ketdi, qayta urinib ko'ring",
  },

  sidebar: {
    category: "Kategoriya",
    reviews: "Binolar",
    admins: "Administratorlar",
    news: "Yangiliklar",
    type: "tur",
    exit: "Chiqish",
    role: "rol",
    top_news:"Top Yangiliklar"
  },

  home: {
    start_time: "boshlanish vaqti",
    end_time: "tugash vaqti",
    budget: "byudjet",
    clients: "mijozlar",
    total_profit: "umumiy foyda",
    expenses: "xarajatlar",
  },

  table: {
    search_by:(e)=> `${e}larni qidirish`,
    loading:"Yuklanmoqda...",
    not_found:"Malumot topilmadi",
    isTop:"Top Yangilik",
    main_image:"Asosiy Rasm",
    images:"Ramslar",
    grafik:"grafik", 
    open_hour: "ochilish vaqti",
    close_hour: "yopilish vaqti",
    address: "Manzil",
    datefrom: (s, e) => `${s} dan ${e} gacha`,
    fuel_type: "yoqilg'i turi",
    max_speed: "maksimal tezlik",
    place: "joy",
    tinting: "tonirovka",
    baggage: "yuk",
    conditioner: "konditsioner",
    false: "mavjud emas",
    true: "mavjud",

    lang: "til",
    star: "yulduz",
    from: "dan",
    ordered: "buyurtma berilgan",
    moving_from_country: "mamlakatdan ko'chirilmoqda",
    entered_to_country: "mamlakatga kirish",
    delivered: "yetkazilgan",
    creator: "yaratuvchi",
    types: "ko'rish filtri",
    all: "hammasi",
    by_category: "kategoriyaga ko'ra",
    by_client: "mijozga ko'ra",
    by_fesclient: "FES mijoziga ko'ra",
    complated: "yakunlandi",
    active: "faol",
    kurs: "kurs",
    card: "karta",
    cash: "naqd pul",
    delivery: "yetkazib berish",
    pickup: "olib ketish",
    inactive: "faol emas",
    payment_method: "to'lov turi",
    shipment_id: "yuk tashish ID",
    custom_date: "moslashtirilgan vaqt",
    residual_amount: "qisqa ma'lumot",
    complated_amount: "uzun ma'lumot",
    complated: "yakunlandi",
    image: "rasm",
    exist: "mavjud",
    deliver_name: "yetkazuvchi ismi",
    deliver_phone: "yetkazuvchi telefoni",
    truck_number: "asosiy",
    add_shipment: "Yuk qo'shish",
    name: "Nomi",
    sale: "savdo",
    title: "sarlavha",
    sale_cost: "savdo narxi",
    sale_amount: "chegirma foizi",
    subtitle: "kichik sarlavha",
    info: "ma'lumot",
    created_at: "yaratilgan vaqti",
    amount: "miqdor",
    overall_price: "Umumiy narx",
    payed_price: "tarkibiy qismlar",
    status: "holat",
    country: "Kategoriya",
    country_number: "buyurtma raqami",
    id: "ID",
    inn: "INN",
    total_amount: "umumiy miqdor",
    type: "Avtomobil turi",
    car_name: "Avtomobil nomi",
    method: "usul",
    uses_date: "foydalanish sanasi",
    seria_id: "pastki",
    sum: "Summasi",
    dollar: "valyutada",
    stock_id: "ombor ID",
    price: "kichik sarlavha",
    client_id: "mijoz ID",
    new_price: "narx",
    direction: "yo'nalish",
    product_name: "mahsulot nomi",
    client_name: "mijoz nomi",
    client_number: "mijoz raqami",
    phone_number: "telefon raqami",
    additional_info: "qo'shimcha ma'lumot",
    expenses_name: "xarajatlar nomi",
    rows_per_page: "Har bir sahifada qatorlar",
    date: "vaqt",
    status: "holat",
    direction: "yo'nalish",
    rejected: "rad etildi",
    accepted: "qabul qilindi",
    reject: "rad etish",
    accept: "qabul qilish",
    pending: "kutilmoqda",
    warehouse: "Ombor",
    employee: "xodim",
    location: "joylashuv",
  },

  modal: {
    add: "Qo'shish",
    edit: "Tahrirlash",
    addProduct: {
      addproduct: "Mahsulot qo'shish",
      editproduct: "Mahsulotni tahrirlash",
      count: "miqdor",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "sotish",
      addtocart: "Savatga qo'shish",
      sale_product: "Mahsulotni sotish",
      total_price: "Umumiy narx",
    },
    addAdmins: {
      adddeliver: "Admin qo'shish",
      editdeliver: "Adminni tahrirlash",
    },
    addNews: {
      addNews: "Yangilik qo'shish",
      editNews: "Yangilikni tahrirlash",
    },
    addBuilding: {
      addbuilding: "Bino qo'shish",
      editbuilding: "Binoni tahrirlash",
    },
    addWarehouse: {
      title: "Brend qo'shish",
      edit: "Brendni tahrirlash",
      transfer_from_werhouse: "Asosiy ombordan o'tkazish",
      transfer_to_werhouse: "Ombordan omborga o'tkazish",
    },
    addNews: {
      addnews: "Yangilik qo'shish",
      editnews: "Yangilikni tahrirlash",
    },
    addExpenses: {
      title: "Xarajatlar qo'shish",
      edit: "Xarajatlarni tahrirlash",
    },
    addIncome: {
      title: "Daromad qo'shish",
      edit: "Daromadni tahrirlash",
    },
    addCategory: {
      title: "Kategoriya qo'shish",
      edit: "Kategoriyani tahrirlash",
      category: "Kategoriya",
      subcategory: "Kichik kategoriya",
      subtitle: "Kichik kategoriya qo'shish",
      subedit: "Kichik kategoriyani tahrirlash",
    },
    addCompany: {
      title: "Kompaniya qo'shish",
      edit: "Kompaniyani tahrirlash",
      category: "Kompaniya",
      subcategory: "hisob raqami",
      subtitle: "Kompaniya hisobini qo'shish",
      subedit: "Kompaniya hisobini tahrirlash",
    },
  },
};

export default header;
