const header = {
  uz: "uzb",
  ru: "rus",
  en: "ing",
  kaa: "kaa",
  action: "harakatlar",
  create: "yaratish",
  delete: "oʻchirish",
  close: "yopish",
  update: "yangilash",
  basket: "Savat",
  transfer: "Oʻtkazma",
  continue: "tasdiqlash",
  login: {
    welcome: "TMA ga xush kelibsiz",
    title: "Kirish",
    password: "Parol",
    enter: "kirish",
    wrongpasswor: "Login yoki parol noto‘g‘ri! Qaytadan urinib ko‘ring",
  },

  alerts: {
    password_incorreect:
      "noto'g'ri parol: parolda kamida bitta katta harf, belgi va raqam bo'lishi kerak, uzunligi 6 dan 30 gacha bo'lishi kerak",
    confirmdelete: "Haqiqatan ham o‘chirmoqchimisiz?",
    ok: "ok",
    no: "bekor qilish",
    inputError: "Bo‘sh qiymat kiritmang",
    nodelete: "ruxsat yo‘q",
    deleted: "Muvaffaqiyatli o‘chirildi",
    added: "Muvaffaqiyatli yaratildi",
    edited: "Muvaffaqiyatli yangilandi",
    slownetwork: "Internet sekin yoki mavjud emas",
    warning: "Nimadir xato ketdi, qaytadan urinib ko‘ring",
  },

  sidebar: {
    news_category: "Yangiliklar kategoriyasi",
    library_category: "Kutubxona kategoriyasi",
    library: "Kutubxona",
    faq_category: "FAQ kategoriyasi",
    faq: "FAQ",
    advertisement: "Reklama",
    advertisement_category: "Reklama kategoriyasi",
    anouncement: "E'lon",
    anouncement_category: "E'lon kategoriyasi",
    anons_network_category: "Anons tarmoq kategoriyasi",
    anons_network_link: "Anons tarmoq havolasi",
    anons_faq: "Anons FAQ",
    story: "Hikoya",
    videos: "Videolar",
    category: "Kategoriya",
    reviews: "Binolar",
    admins: "Administratorlar",
    news: "Yangiliklar",
    type: "tur",
    exit: "Chiqish",
    role: "rol",
    top_news: "Eng so‘nggi yangiliklar",
  },

  home: {
    start_time: "boshlanish vaqti",
    end_time: "tugash vaqti",
    budget: "byudjet",
    clients: "mijozlar",
    total_profit: "umumiy foyda",
    expenses: "xarajatlar",
  },

  table: {
    link: "Havola",
    construction_date: "qurilish sanasi",
    zip_code: "pochta indeksi",
    floors: "qavatlar",
    video: "video",
    state: "shtat",
    city: "shahar",
    search_by: (e) => `${e} bo‘yicha qidirish`,
    loading: "Yuklanmoqda...",
    not_found: "Ma'lumot topilmadi",
    isTop: "Eng so‘nggi yangiliklar",
    isFree: "Bepul",
    main_image: "Muqova rasmi",
    images: "Rasmlar",
    file: "Fayl",
    grafik: "grafik",
    open_hour: "ochilish vaqti",
    close_hour: "yopilish vaqti",
    address: "Manzil",
    datefrom: (s, e) => `${s} dan ${e} gacha`,
    fuel_type: "yoqilg'i turi",
    max_speed: "maksimal tezlik",
    place: "joy",
    tinting: "tonirovka",
    baggage: "yuk",
    conditioner: "konditsioner",
    false: "mavjud emas",
    true: "mavjud",
    view_count: "ko‘rishlar soni",
    lang: "til",
    star: "yulduz",
    from: "dan",
    ordered: "buyurtma berilgan",
    moving_from_country: "kelayotgan mamlakat",
    entered_to_country: "kirgan mamlakat",
    delivered: "yetkazildi",
    creator: "yaratuvchi",
    types: "ko‘rish filtri",
    all: "barchasi",
    by_category: "kategoriya bo‘yicha",
    by_client: "mijoz bo‘yicha",
    by_fesclient: "FES mijoz bo‘yicha",
    complated: "yakunlangan",
    active: "faol",
    kurs: "kurs",
    card: "karta",
    cash: "naqd",
    delivery: "yetkazib berish",
    pickup: "olib ketish",
    inactive: "faol emas",
    payment_method: "to‘lov usuli",
    shipment_id: "jo‘natma IDsi",
    custom_date: "maxsus vaqt",
    residual_amount: "qisqa ma'lumot",
    complated_amount: "to‘liq ma'lumot",
    image: "rasm",
    exist: "mavjud",
    deliver_name: "yetkazuvchi ismi",
    deliver_phone: "yetkazuvchi telefoni",
    truck_number: "asosiy",
    add_shipment: "Jo‘natma qo‘shish",
    name: "Ism",
    sale: "chegirma",
    title: "sarlavha",
    cost: "narx",
    author: "muallif",
    sale_amount: "chegirma foizi",
    subtitle: "quyi sarlavha",
    info: "ma'lumot",
    raiting: "reyting",
    like_count: "layklar",
    download_count: "yuklashlar",
    created_at: "yaratilgan sana",
    amount: "miqdor",
    overall_price: "umumiy narx",
    payed_price: "tarkibiy qismlar",
    status: "holat",
    answer: "javob",
    question: "savol",
    country: "Kategoriya",
    country_number: "buyurtma raqami",
    id: "ID",
    inn: "INN",
    total_amount: "umumiy summa",
    type: "turi",
    car_name: "avto nomi",
    method: "usul",
    uses_date: "foydalanish sanasi",
    seria_id: "quyi",
    sum: "Summa",
    dollar: "valutada",
    stock_id: "ombor ID",
    price: "quyi sarlavha",
    client_id: "mijoz IDsi",
    new_price: "narx",
    direction: "yo‘nalish",
    product_name: "mahsulot nomi",
    client_name: "mijoz ismi",
    client_number: "mijoz raqami",
    phone_number: "telefon raqami",
    additional_info: "qo‘shimcha ma'lumot",
    expenses_name: "xarajat nomi",
    rows_per_page: "Sahifadagi qatorlar",
    date: "vaqt",
    rejected: "rad etilgan",
    accepted: "qabul qilingan",
    reject: "rad etish",
    accept: "qabul qilish",
    pending: "kutilmoqda",
    warehouse: "Ombor",
    employee: "xodim",
    location: "joylashuv",
  },

  modal: {
    add: "Qo‘shish",
    edit: "Tahrirlash",
    add_title: (title) => `${title} qo‘shish`,
    edit_title: (title) => `${title}ni tahrirlash`,
    addProduct: {
      addproduct: "Mahsulot qo‘shish",
      editproduct: "Mahsulotni tahrirlash",
      count: "miqdor",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "chegirma",
      addtocart: "Savatchaga qo‘shish",
      sale_product: "Mahsulotni sotish",
      total_price: "Umumiy narx",
    },
    addAdmins: {
      adddeliver: "Admin qo‘shish",
      editdeliver: "Adminni tahrirlash",
    },
    addNews: {
      addnews: "Yangilik qo‘shish",
      editnews: "Yangilikni tahrirlash",
      addNews: "Yangilik qo‘shish",
      editNews: "Yangilikni tahrirlash",
    },
    addBuilding: {
      addbuilding: "Bino qo‘shish",
      editbuilding: "Binoni tahrirlash",
    },
    addWarehouse: {
      title: "Brend qo‘shish",
      edit: "Brendni tahrirlash",
      transfer_from_werhouse: "Asosiy omborddan o'tkazish",
      transfer_to_werhouse: "Omborlar orasida o'tkazish",
    },
    addExpenses: {
      title: "Xarajat qo‘shish",
      edit: "Xarajatni tahrirlash",
    },
    addIncome: {
      title: "Daromad qo‘shish",
      edit: "Daromadni tahrirlash",
    },
    addCategory: {
      title: "Kategoriya qo‘shish",
      edit: "Kategoriyani tahrirlash",
      category: "Kategoriya",
      subcategory: "Subkategoriya",
      subtitle: "Subkategoriya qo‘shish",
      subedit: "Subkategoriya tahrirlash",
    },
    addCompany: {
      title: "Kompaniya qo‘shish",
      edit: "Kompaniyani tahrirlash",
      category: "Kompaniya",
      subcategory: "hisob raqami",
      subtitle: "Kompaniya hisob raqami qo‘shish",
      subedit: "Hisob raqamini tahrirlash",
    },
  },
};

export default header;
