const header = {
  uz: "uz",
  ru: "ru",
  en: "ang",
  kaa: "kaa",
  action: "harakatlar",
  create: "yaratish",
  delete: "o‘chirish",
  close: "yopish",
  update: "yangilash",
  basket: "Savat",
  transfer: "O‘tkazish",
  continue: "tasdiqlash",
  login: {
    welcome: "TMAga xush kelibsiz",
    title: "Kirish",
    password: "Parol",
    enter: "kirish",
    wrongpasswor: "Noto‘g‘ri foydalanuvchi nomi yoki parol! Qaytadan urinib ko‘ring",
  },

  alerts: {
    password_incorreect:
      "noto‘g‘ri parol: parolda kamida bitta bosh harf, belgi va raqam bo‘lishi, hamda 6 dan 30 tagacha belgi bo‘lishi kerak",
    confirmdelete: "Haqiqatan ham o‘chirishni xohlaysizmi?",
    ok: "OK",
    no: "bekor qilish",
    inputError: "Bo‘sh maydon kiritmang",
    nodelete: "ruxsat yo‘q",
    deleted: "Muvaffaqiyatli o‘chirildi",
    added: "Muvaffaqiyatli yaratildi",
    edited: "Muvaffaqiyatli yangilandi",
    slownetwork: "Internet sekin ishlayapti yoki mavjud emas",
    warning: "Nimadir noto‘g‘ri ketdi, qaytadan urinib ko‘ring",
  },

  sidebar: {
    news_category: "Yangiliklar kategoriyasi",
    library_category: "Kutubxona kategoriyasi",
    library: "Kutubxona",
    faq_category: "FAQ kategoriyasi",
    faq: "FAQ",
    advertisement: "Reklama",
    advertisement_category: "Reklama kategoriyasi",
    anouncement: "E'lon",
    anouncement_category: "E'lon kategoriyasi",
    anons_network_category: "Tarmoq e'loni kategoriyasi",
    anons_network_link: "Tarmoq e'loni havolasi",
    anons_faq: "E'lon FAQ",
    story: "Hikoya",
    videos: "Videolar",
    category: "Kategoriya",
    reviews: "Bino sharhlari",
    admins: "Administratorlar",
    news: "Yangiliklar",
    type: "Turi",
    exit: "Chiqish",
    role: "Roli",
    top_news: "Asosiy yangiliklar",
  },

  home: {
    start_time: "boshlanish vaqti",
    end_time: "tugash vaqti",
    budget: "budjet",
    clients: "mijozlar",
    total_profit: "umumiy foyda",
    expenses: "xarajatlar",
  },

  table: {
    link: "Havola",
    construction_date: "qurilish sanasi",
    zip_code: "pochta indeksi",
    floors: "qavatlar",
    video: "video",
    state: "viloyat",
    city: "shahar",
    search_by: (e) => `${e} bo‘yicha qidirish`,
    loading: "Yuklanmoqda...",
    not_found: "Ma'lumot topilmadi",
    isTop: "Asosiy yangiliklar",
    isFree: "Bepul",
    main_image: "Muqova surati",
    images: "Rasmlar",
    file: "Fayl",
    grafik: "Grafik",
    open_hour: "ochilish vaqti",
    close_hour: "yopilish vaqti",
    address: "Manzil",
    datefrom: (s, e) => `${s} dan ${e} gacha`,
    fuel_type: "yoqilg‘i turi",
    max_speed: "maksimal tezlik",
    place: "joy",
    tinting: "tonirovka",
    baggage: "yukxonasi",
    conditioner: "konditsioner",
    false: "mavjud emas",
    true: "mavjud",
    view_count: "ko‘rishlar soni",
    lang: "til",
    star: "yulduz",
    from: "dan",
    ordered: "buyurtma qilingan",
    moving_from_country: "davlatdan chiqish",
    entered_to_country: "davlatga kirish",
    delivered: "yetkazildi",
    creator: "yaratuvchi",
    types: "ko‘rish filtri",
    all: "barchasi",
    by_category: "kategoriya bo‘yicha",
    by_client: "mijoz bo‘yicha",
    by_fesclient: "FES mijoz bo‘yicha",
    complated: "yakunlandi",
    active: "faol",
    kurs: "kurs",
    card: "karta",
    cash: "naqd",
    delivery: "yetkazib berish",
    pickup: "o‘zi olib ketish",
    inactive: "faol emas",
    payment_method: "to‘lov usuli",
    shipment_id: "yuk ID",
    custom_date: "maxsus sana",
    residual_amount: "qisqa ma'lumot",
    complated_amount: "to‘liq ma'lumot",
    image: "rasm",
    exist: "mavjud",
    deliver_name: "yetkazuvchi ismi",
    deliver_phone: "yetkazuvchi telefoni",
    truck_number: "avtomobil raqami",
    add_shipment: "Yuk qo‘shish",
    name: "Nomi",
    sale: "chegirma",
    title: "sarlavha",
    cost: "narx",
    author: "muallif",
    sale_amount: "chegirma foizi",
    subtitle: "qo‘shimcha sarlavha",
    info: "ma'lumot",
    raiting: "reyting",
    like_count: "yoqtirishlar",
    download_count: "yuklab olishlar",
    created_at: "yaratilgan sana",
    amount: "miqdor",
    overall_price: "umumiy narx",
    payed_price: "tarkib",
    status: "holat",
    answer: "javob",
    question: "savol",
    country: "Kategoriya",
    country_number: "buyurtma raqami",
    id: "ID",
    inn: "INN",
    total_amount: "umumiy miqdor",
    type: "Avtomobil turi",
    car_name: "Avtomobil nomi",
    method: "usul",
    uses_date: "foydalanish sanasi",
    seria_id: "seriya ID",
    sum: "So‘m",
    dollar: "valyutada",
    stock_id: "ombor ID",
    price: "narx",
    client_id: "mijoz ID",
    new_price: "yangilangan narx",
    direction: "yo‘nalish",
    product_name: "mahsulot nomi",
    client_name: "mijoz nomi",
    client_number: "mijoz raqami",
    phone_number: "telefon raqami",
    additional_info: "qo‘shimcha ma'lumot",
    expenses_name: "xarajat nomi",
    rows_per_page: "Sahifadagi qatorlar",
    date: "sana",
    rejected: "rad etildi",
    accepted: "qabul qilindi",
    reject: "rad etish",
    accept: "qabul qilish",
    pending: "kutilmoqda",
    warehouse: "Ombor",
    employee: "xodim",
    location: "joylashuv",
  },

  modal: {
    add: "Qo‘shish",
    edit: "Tahrirlash",
    add_title: (title) => `${title} qo‘shish`,
    edit_title: (title) => `${title} tahrirlash`,
    addProduct: {
      addproduct: "Mahsulot qo‘shish",
      editproduct: "Mahsulot tahrirlash",
      count: "miqdor",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "chegirma",
      addtocart: "Savatchaga qo‘shish",
      sale_product: "Mahsulot sotish",
      total_price: "Umumiy narx",
    },
  },
};

export default header;
