const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  action: "действия",
  create: "создать",
  delete: "удалить",
  update: "изменить",
  basket: "Корзина",
  transfer: "Передача",
  continue: "подтвердить",
  login: {
    welcome: "Добро пожаловать в TMA",
    title: "Войти",
    password: "Пароль",
    enter: "войти",
    wrongpassword: "Неверное имя пользователя или пароль! Попробуйте снова"
  },
  alerts: {
    password_incorrect: "Пароль неверен: он должен содержать хотя бы одну заглавную букву, специальный символ и цифру, а также быть от 6 до 30 символов в длину",
    confirmdelete: "Вы уверены, что хотите удалить?",
    ok: "OK",
    no: "Отмена",
    inputError: "Не оставляйте поля пустыми",
    nodelete: "Нет разрешения",
    deleted: "Успешно удалено",
    added: "Успешно создано",
    edited: "Успешно изменено",
    slownetwork: "Интернет медленный или недоступен",
    warning: "Что-то пошло не так, попробуйте снова"
  },
  sidebar: {
    category: "Категория",
    reviews: "Здания",
    admins: "Администраторы",
    news: "Новости",
    type: "тип",
    exit: "Выйти",
    role: "роль"
  },
  home: {
    start_time: "время начала",
    end_time: "время окончания",
    budget: "бюджет",
    clients: "клиенты",
    total_profit: "общая прибыль",
    expenses: "расходы"
  },
  table: {
    search_by:"искать",
    grafik: "график",
    open_hour: "время открытия",
    close_hour: "время закрытия",
    address: "адрес",
    datefrom: (s, e) => `${s} по ${e}`,
    fuel_type: "тип топлива",
    max_speed: "максимальная скорость",
    place: "место",
    tinting: "тонировка",
    baggage: "багаж",
    conditioner: "кондиционер",
    false: "не доступен",
    true: "доступен",
    lang: "язык",
    star: "звезда",
    from: "от",
    ordered: "заказано",
    moving_from_country: "перемещение из страны",
    entered_to_country: "вход в страну",
    delivered: "доставлено",
    creator: "создатель",
    types: "фильтр просмотра",
    all: "все",
    by_category: "по категории",
    by_client: "по клиенту",
    by_fesclient: "по клиенту FES",
    complated: "завершено",
    active: "активный",
    kurs: "курс",
    card: "карта",
    cash: "наличные",
    delivery: "доставка",
    pickup: "самовывоз",
    inactive: "неактивный",
    payment_method: "метод оплаты",
    shipment_id: "ID отправления",
    custom_date: "индивидуальное время",
    residual_amount: "остаточная сумма",
    complated_amount: "подробное описание",
    image: "изображение",
    exist: "существует",
    deliver_name: "имя доставщика",
    deliver_phone: "телефон доставщика",
    truck_number: "номер грузовика",
    add_shipment: "Добавить отправление",
    name: "Имя",
    sale: "продажа",
    title: "заголовок",
    sale_cost: "цена продажи",
    sale_amount: "процент скидки",
    subtitle: "подзаголовок",
    info: "информация",
    created_at: "создано в",
    amount: "сумма",
    overall_price: "Общая цена",
    payed_price: "оплаченная часть",
    status: "статус",
    country: "Страна",
    country_number: "номер заказа",
    id: "ID",
    inn: "ИНН",
    total_amount: "общая сумма",
    type: "Тип автомобиля",
    car_name: "Название автомобиля",
    method: "метод",
    uses_date: "дата использования",
    seria_id: "серийный номер",
    sum: "Сумма",
    dollar: "в валюте",
    stock_id: "ID склада",
    price: "цена",
    client_id: "ID клиента",
    new_price: "новая цена",
    direction: "направление",
    product_name: "название продукта",
    client_name: "имя клиента",
    client_number: "номер клиента",
    phone_number: "номер телефона",
    additional_info: "дополнительная информация",
    expenses_name: "название расходов",
    rows_per_page: "Строк на странице",
    date: "дата",
    status: "статус",
    direction: "направление",
    rejected: "отклонено",
    accepted: "принято",
    reject: "отклонить",
    accept: "принять",
    pending: "ожидание",
    warehouse: "Склад",
    employee: "сотрудник",
    location: "местоположение"
  },
  modal: {
    add: "Добавить",
    edit: "Изменить",
    addProduct: {
      addproduct: "Добавить продукт",
      editproduct: "Изменить продукт",
      count: "количество",
      kg: "кг",
      liter: "литр",
      meter: "метр",
      sale: "продажа",
      addtocart: "Добавить в корзину",
      sale_product: "Продажа продукта",
      total_price: "Общая цена"
    },
    addAdmins: {
      adddeliver: "Добавить администратора",
      editdeliver: "Изменить администратора"
    },
    addNews: {
      addNews: "Добавить новость",
      editNews: "Изменить новость"
    },
    addBuilding: {
      addbuilding: "Добавить здание",
      editbuilding: "Изменить здание"
    },
    addWarehouse: {
      title: "Добавить бренд",
      edit: "Изменить бренд",
      transfer_from_werhouse: "Перевод из основного склада",
      transfer_to_werhouse: "Перевод между складами"
    },
    addExpenses: {
      title: "Добавить расходы",
      edit: "Изменить расходы"
    },
    addIncome: {
      title: "Добавить доход",
      edit: "Изменить доход"
    },
    addCategory: {
      title: "Добавить категорию",
      edit: "Изменить категорию",
      category: "Категория",
      subcategory: "Подкатегория",
      subtitle: "Добавить подкатегорию",
      subedit: "Изменить подкатегорию"
    },
    addCompany: {
      title: "Добавить компанию",
      edit: "Изменить компанию",
      category: "Компания",
      subcategory: "номер счета",
      subtitle: "Добавить счет компании",
      subedit: "Изменить счет компании"
    }
  }
};

export default header;
