const header = {
  uz: "узб",
  ru: "рус",
  en: "анг",
  kaa: "каа",
  action: "действия",
  create: "создать",
  delete: "удалить",
  close: "закрыть",
  update: "обновить",
  basket: "Корзина",
  transfer: "Перевод",
  continue: "подтвердить",
  login: {
    welcome: "Добро пожаловать в TMA",
    title: "Вход",
    password: "Пароль",
    enter: "войти",
    wrongpasswor: "Неверное имя пользователя или пароль! Пожалуйста, попробуйте снова",
  },

  alerts: {
    password_incorreect:
      "неверный пароль: пароль должен содержать хотя бы одну заглавную букву, символ и цифру, длина от 6 до 30 символов",
    confirmdelete: "Вы уверены, что хотите удалить?",
    ok: "ок",
    no: "отмена",
    inputError: "Не вводите пустые данные",
    nodelete: "нет доступа",
    deleted: "Успешно удалено",
    added: "Успешно создано",
    edited: "Успешно обновлено",
    slownetwork: "Интернет медленный или недоступен",
    warning: "что-то пошло не так, попробуйте еще раз",
  },

  sidebar: {
    news_category: "Категория новостей",
    library_category: "Категория библиотеки",
    library: "Библиотека",
    faq_category: "Категория FAQ",
    faq: "FAQ",
    advertisement: "Реклама",
    advertisement_category: "Категория рекламы",
    anouncement: "Объявление",
    anouncement_category: "Категория объявлений",
    anons_network_category: "Категория сети анонсов",
    anons_network_link: "Ссылка на сеть анонсов",
    anons_faq: "FAQ анонсов",
    story: "История",
    videos: "Видео",
    category: "Категория",
    reviews: "Здания",
    admins: "Администраторы",
    news: "Новости",
    type: "тип",
    exit: "Выход",
    role: "роль",
    top_news: "Главные новости",
  },

  home: {
    start_time: "время начала",
    end_time: "время окончания",
    budget: "бюджет",
    clients: "клиенты",
    total_profit: "общая прибыль",
    expenses: "расходы",
  },

  table: {
    link: "Ссылка",
    construction_date: "дата постройки",
    zip_code: "почтовый индекс",
    floors: "этажи",
    video: "видео",
    state: "штат",
    city: "город",
    search_by: (e) => `Поиск по ${e}`,
    loading: "Загрузка...",
    not_found: "Данные не найдены",
    isTop: "Главные новости",
    isFree: "Бесплатно",
    main_image: "Обложка",
    images: "Изображения",
    file: "Файл",
    grafik: "график",
    open_hour: "время открытия",
    close_hour: "время закрытия",
    address: "Адрес",
    datefrom: (s, e) => `С ${s} по ${e}`,
    fuel_type: "тип топлива",
    max_speed: "макс. скорость",
    place: "место",
    tinting: "тонировка",
    baggage: "багаж",
    conditioner: "кондиционер",
    false: "недоступно",
    true: "доступно",
    view_count: "кол-во просмотров",
    lang: "язык",
    star: "звезда",
    from: "от",
    ordered: "заказано",
    moving_from_country: "переезд из страны",
    entered_to_country: "въехал в страну",
    delivered: "доставлено",
    creator: "создатель",
    types: "фильтр по виду",
    all: "все",
    by_category: "по категории",
    by_client: "по клиенту",
    by_fesclient: "по FES клиенту",
    complated: "завершено",
    active: "активно",
    kurs: "курс",
    card: "карта",
    cash: "наличные",
    delivery: "доставка",
    pickup: "самовывоз",
    inactive: "неактивно",
    payment_method: "способ оплаты",
    shipment_id: "ID отправки",
    custom_date: "пользовательское время",
    residual_amount: "краткая информация",
    complated_amount: "подробная информация",
    image: "изображение",
    exist: "доступно",
    deliver_name: "имя доставщика",
    deliver_phone: "телефон доставщика",
    truck_number: "основной",
    add_shipment: "Добавить отправку",
    name: "Имя",
    sale: "скидка",
    title: "заголовок",
    cost: "цена",
    author: "автор",
    sale_amount: "процент скидки",
    subtitle: "подзаголовок",
    info: "информация",
    raiting: "рейтинг",
    like_count: "лайки",
    download_count: "загрузки",
    created_at: "дата создания",
    amount: "кол-во",
    overall_price: "итоговая цена",
    payed_price: "компоненты",
    status: "статус",
    answer: "ответ",
    question: "вопрос",
    country: "Категория",
    country_number: "номер заказа",
    id: "ID",
    inn: "ИНН",
    total_amount: "общая сумма",
    type: "тип авто",
    car_name: "название авто",
    method: "метод",
    uses_date: "дата использования",
    seria_id: "нижний",
    sum: "Сумма",
    dollar: "в валюте",
    stock_id: "ID склада",
    price: "подзаголовок",
    client_id: "ID клиента",
    new_price: "цена",
    direction: "направление",
    product_name: "название продукта",
    client_name: "имя клиента",
    client_number: "номер клиента",
    phone_number: "номер телефона",
    additional_info: "доп. информация",
    expenses_name: "название расхода",
    rows_per_page: "Строк на странице",
    date: "время",
    rejected: "отклонено",
    accepted: "принято",
    reject: "отклонить",
    accept: "принять",
    pending: "в ожидании",
    warehouse: "Склад",
    employee: "сотрудник",
    location: "местоположение",
  },

  modal: {
    add: "Добавить",
    edit: "Редактировать",
    add_title: (title) => `Добавить ${title}`,
    edit_title: (title) => `Редактировать ${title}`,
    addProduct: {
      addproduct: "Добавить продукт",
      editproduct: "Редактировать продукт",
      count: "количество",
      kg: "кг",
      liter: "литр",
      meter: "метр",
      sale: "скидка",
      addtocart: "Добавить в корзину",
      sale_product: "Продать продукт",
      total_price: "Итоговая цена",
    },
    addAdmins: {
      adddeliver: "Добавить админа",
      editdeliver: "Редактировать админа",
    },
    addNews: {
      addnews: "Добавить новость",
      editnews: "Редактировать новость",
      addNews: "Добавить новость",
      editNews: "Редактировать новость",
    },
    addBuilding: {
      addbuilding: "Добавить здание",
      editbuilding: "Редактировать здание",
    },
    addWarehouse: {
      title: "Добавить бренд",
      edit: "Редактировать бренд",
      transfer_from_werhouse: "Перевод из главного склада",
      transfer_to_werhouse: "Перевод между складами",
    },
    addExpenses: {
      title: "Добавить расход",
      edit: "Редактировать расход",
    },
    addIncome: {
      title: "Добавить доход",
      edit: "Редактировать доход",
    },
    addCategory: {
      title: "Добавить категорию",
      edit: "Редактировать категорию",
      category: "Категория",
      subcategory: "Подкатегория",
      subtitle: "Добавить подкатегорию",
      subedit: "Редактировать подкатегорию",
    },
    addCompany: {
      title: "Добавить компанию",
      edit: "Редактировать компанию",
      category: "Компания",
      subcategory: "номер счета",
      subtitle: "Добавить счет компании",
      subedit: "Редактировать счет компании",
    },
  },
};

export default header;
