const header = {
  uz: "уз",
  ru: "ру",
  en: "ен",
  action: "действия",
  create: "создать",
  delete: "удалить",
  close: "закрыть",
  update: "обновить",
  basket: "Корзина",
  transfer: "Перевод",
  continue: "подтвердить",
  login: {
    welcome: "Добро пожаловать в TMA",
    title: "Вход",
    password: "Пароль",
    enter: "войти",
    wrongpasswor: "Неправильное имя пользователя или пароль! Пожалуйста, попробуйте снова",
  },

  alerts: {
    password_incorreect:
      "неправильный пароль: пароль должен содержать хотя бы одну заглавную букву, символ и цифру, и быть длиной от 6 до 30 символов",
    confirmdelete: "Вы уверены, что хотите удалить?",
    ok: "ок",
    no: "отменить",
    inputError: "Не вводите пустые данные",
    nodelete: "нет разрешения",
    deleted: "Успешно удалено",
    added: "Успешно создано",
    edited: "Успешно изменено",
    slownetwork: "Интернет медленный или недоступен",
    warning: "что-то пошло не так, попробуйте снова",
  },

  sidebar: {
    category: "Категория",
    reviews: "Здания",
    admins: "Администраторы",
    news: "Новости",
    type: "тип",
    exit: "Выход",
    role: "роль",
    top_news: "Топ Новости",
  },

  home: {
    start_time: "время начала",
    end_time: "время окончания",
    budget: "бюджет",
    clients: "клиенты",
    total_profit: "общая прибыль",
    expenses: "расходы",
  },

  table: {
    search_by: (e) => `Поиск по ${e}`,
    loading: "Загрузка...",
    not_found: "Данные не найдены",
    isTop: "Топ Новости",
    main_image: "Главное Изображение",
    images: "Изображения",
    grafik: "график",
    open_hour: "время открытия",
    close_hour: "время закрытия",
    address: "Адрес",
    datefrom: (s, e) => `С ${s} до ${e}`,
    fuel_type: "тип топлива",
    max_speed: "максимальная скорость",
    place: "место",
    tinting: "тонировка",
    baggage: "багаж",
    conditioner: "кондиционер",
    false: "недоступно",
    true: "доступно",

    lang: "язык",
    star: "звезда",
    from: "из",
    ordered: "заказано",
    moving_from_country: "перемещается из страны",
    entered_to_country: "въехал в страну",
    delivered: "доставлено",
    creator: "создатель",
    types: "фильтр просмотра",
    all: "все",
    by_category: "по категории",
    by_client: "по клиенту",
    by_fesclient: "по клиенту ФЕС",
    complated: "завершено",
    active: "активный",
    kurs: "курс",
    card: "карта",
    cash: "наличные",
    delivery: "доставка",
    pickup: "самовывоз",
    inactive: "неактивный",
    payment_method: "способ оплаты",
    shipment_id: "ID доставки",
    custom_date: "настраиваемое время",
    residual_amount: "краткая информация",
    complated_amount: "длинная информация",
    complated: "завершено",
    image: "изображение",
    exist: "доступно",
    deliver_name: "имя доставщика",
    deliver_phone: "телефон доставщика",
    truck_number: "основной",
    add_shipment: "Добавить Доставку",
    name: "Название",
    sale: "продажа",
    title: "заголовок",
    sale_cost: "цена продажи",
    sale_amount: "процент скидки",
    subtitle: "подзаголовок",
    info: "информация",
    created_at: "создано",
    amount: "количество",
    overall_price: "Общая цена",
    payed_price: "компоненты",
    status: "статус",
    country: "Категория",
    country_number: "номер заказа",
    id: "ID",
    inn: "ИНН",
    total_amount: "общая сумма",
    type: "Тип автомобиля",
    car_name: "Название автомобиля",
    method: "метод",
    uses_date: "дата использования",
    seria_id: "нижний",
    sum: "Сумма",
    dollar: "в валюте",
    stock_id: "ID склада",
    price: "подзаголовок",
    client_id: "ID клиента",
    new_price: "цена",
    direction: "направление",
    product_name: "название продукта",
    client_name: "имя клиента",
    client_number: "номер клиента",
    phone_number: "номер телефона",
    additional_info: "дополнительная информация",
    expenses_name: "название расходов",
    rows_per_page: "Строк на странице",
    date: "время",
    status: "статус",
    direction: "направление",
    rejected: "отклонено",
    accepted: "принято",
    reject: "отклонить",
    accept: "принять",
    pending: "в ожидании",
    warehouse: "Склад",
    employee: "сотрудник",
    location: "местоположение",
  },

  modal: {
    add: "Добавить",
    edit: "Редактировать",
    addProduct: {
      addproduct: "Добавить Продукт",
      editproduct: "Редактировать Продукт",
      count: "количество",
      kg: "кг",
      liter: "литр",
      meter: "метр",
      sale: "продажа",
      addtocart: "Добавить в Корзину",
      sale_product: "Продать Продукт",
      total_price: "Общая цена",
    },
    addAdmins: {
      adddeliver: "Добавить Админа",
      editdeliver: "Редактировать Админа",
    },
    addNews: {
      addNews: "Добавить Новость",
      editNews: "Редактировать Новость",
    },
    addBuilding: {
      addbuilding: "Добавить Здание",
      editbuilding: "Редактировать Здание",
    },
    addWarehouse: {
      title: "Добавить Бренд",
      edit: "Редактировать Бренд",
      transfer_from_werhouse: "Перевод из Основного Склада",
      transfer_to_werhouse: "Перевод со Склада на Склад",
    },
    addNews: {
      addnews: "Добавить Новость",
      editnews: "Редактировать Новость",
    },
    addExpenses: {
      title: "Добавить Расходы",
      edit: "Редактировать Расходы",
    },
    addIncome: {
      title: "Добавить Доход",
      edit: "Редактировать Доход",
    },
    addCategory: {
      title: "Добавить Категорию",
      edit: "Редактировать Категорию",
      category: "Категория",
      subcategory: "Подкатегория",
      subtitle: "Добавить Подкатегорию",
      subedit: "Редактировать Подкатегорию",
    },
    addCompany: {
      title: "Добавить Компанию",
      edit: "Редактировать Компанию",
      category: "Компания",
      subcategory: "номер счета",
      subtitle: "Добавить Счет Компании",
      subedit: "Редактировать Счет Компании",
    },
  },
};

export default header;
