const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  action: "actions",
  create: "create",
  delete: "delete",
  close: "close",
  update: "update",
  basket: "Basket",
  transfer: "Transfer",
  continue: "confirm",
  login: {
    welcome: "Welcome to TMA",
    title: "Login",
    password: "Password",
    enter: "login",
    wrongpasswor: "Incorrect username or password! Please try again",
  },

  alerts: {
    password_incorreect:
      "incorrect password: the password must contain at least one uppercase letter, symbol, and number, and must be between 6 to 30 characters long",
    confirmdelete: "Are you sure you want to delete?",
    ok: "ok",
    no: "cancel",
    inputError: "Do not enter empty data",
    nodelete: "no permission",
    deleted: "Successfully deleted",
    added: "Successfully created",
    edited: "Successfully updated",
    slownetwork: "The internet is slow or unavailable",
    warning: "something went wrong, please try again",
  },

  sidebar: {
    category: "Category",
    reviews: "Buildings",
    admins: "Administrators",
    news: "News",
    type: "type",
    exit: "Logout",
    role: "role",
    top_news: "Top News",
  },

  home: {
    start_time: "start time",
    end_time: "end time",
    budget: "budget",
    clients: "clients",
    total_profit: "total profit",
    expenses: "expenses",
  },

  table: {
    search_by: (e) => `Search for ${e}`,
    loading: "Loading...",
    not_found: "Data not found",
    isTop: "Top News",
    main_image: "Main Image",
    images: "Images",
    grafik: "graph",
    open_hour: "opening time",
    close_hour: "closing time",
    address: "Address",
    datefrom: (s, e) => `From ${s} to ${e}`,
    fuel_type: "fuel type",
    max_speed: "maximum speed",
    place: "place",
    tinting: "tinting",
    baggage: "luggage",
    conditioner: "air conditioner",
    false: "not available",
    true: "available",

    lang: "language",
    star: "star",
    from: "from",
    ordered: "ordered",
    moving_from_country: "moving from country",
    entered_to_country: "entered to country",
    delivered: "delivered",
    creator: "creator",
    types: "view filter",
    all: "all",
    by_category: "by category",
    by_client: "by client",
    by_fesclient: "by FES client",
    complated: "completed",
    active: "active",
    kurs: "course",
    card: "card",
    cash: "cash",
    delivery: "delivery",
    pickup: "pickup",
    inactive: "inactive",
    payment_method: "payment method",
    shipment_id: "shipment ID",
    custom_date: "custom time",
    residual_amount: "short info",
    complated_amount: "long info",
    complated: "completed",
    image: "image",
    exist: "available",
    deliver_name: "deliverer name",
    deliver_phone: "deliverer phone",
    truck_number: "main",
    add_shipment: "Add Shipment",
    name: "Name",
    sale: "sale",
    title: "title",
    sale_cost: "sale price",
    sale_amount: "discount percentage",
    subtitle: "subtitle",
    info: "info",
    created_at: "created at",
    amount: "amount",
    overall_price: "Total price",
    payed_price: "components",
    status: "status",
    country: "Category",
    country_number: "order number",
    id: "ID",
    inn: "INN",
    total_amount: "total amount",
    type: "Car type",
    car_name: "Car name",
    method: "method",
    uses_date: "use date",
    seria_id: "lower",
    sum: "Amount",
    dollar: "in currency",
    stock_id: "warehouse ID",
    price: "subtitle",
    client_id: "client ID",
    new_price: "price",
    direction: "direction",
    product_name: "product name",
    client_name: "client name",
    client_number: "client number",
    phone_number: "phone number",
    additional_info: "additional information",
    expenses_name: "expenses name",
    rows_per_page: "Rows per page",
    date: "time",
    status: "status",
    direction: "direction",
    rejected: "rejected",
    accepted: "accepted",
    reject: "reject",
    accept: "accept",
    pending: "pending",
    warehouse: "Warehouse",
    employee: "employee",
    location: "location",
  },

  modal: {
    add: "Add",
    edit: "Edit",
    addProduct: {
      addproduct: "Add Product",
      editproduct: "Edit Product",
      count: "quantity",
      kg: "kg",
      liter: "liter",
      meter: "meter",
      sale: "sale",
      addtocart: "Add to Cart",
      sale_product: "Sell Product",
      total_price: "Total price",
    },
    addAdmins: {
      adddeliver: "Add Admin",
      editdeliver: "Edit Admin",
    },
    addNews: {
      addNews: "Add News",
      editNews: "Edit News",
    },
    addBuilding: {
      addbuilding: "Add Building",
      editbuilding: "Edit Building",
    },
    addWarehouse: {
      title: "Add Brand",
      edit: "Edit Brand",
      transfer_from_werhouse: "Transfer from Main Warehouse",
      transfer_to_werhouse: "Transfer from Warehouse to Warehouse",
    },
    addNews: {
      addnews: "Add News",
      editnews: "Edit News",
    },
    addExpenses: {
      title: "Add Expenses",
      edit: "Edit Expenses",
    },
    addIncome: {
      title: "Add Income",
      edit: "Edit Income",
    },
    addCategory: {
      title: "Add Category",
      edit: "Edit Category",
      category: "Category",
      subcategory: "Subcategory",
      subtitle: "Add Subcategory",
      subedit: "Edit Subcategory",
    },
    addCompany: {
      title: "Add Company",
      edit: "Edit Company",
      category: "Company",
      subcategory: "account number",
      subtitle: "Add Company Account",
      subedit: "Edit Company Account",
    },
  },
};

export default header;
